name: Tests

on:
  push:
  schedule:
    - cron:  "0 7 * * 1,3"

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -e .[asgi-file-uploads,tracing,test,dev]
    - name: Pytest
      run: |
        pytest --cov=ariadne --cov=tests
    - uses: codecov/codecov-action@v3
    - name: Linters
      run: |
        pylint ariadne tests
        mypy ariadne tests_mypy --ignore-missing-imports --check-untyped-defs
        black --check .

  fastapi:

    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install wheel
        pip install -r tests_integration/fastapi/requirements.txt
        pip install -e .[asgi-file-uploads,tracing,test,dev]
    - name: Pytest
      run: |
        pytest tests_integration/fastapi
